<?php

namespace App\Repository;

/**
 * CitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeasurementsRepository extends \Doctrine\ORM\EntityRepository
{
}
